import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for ROS 2 Robotic Nervous System
  tutorialSidebar: [
    {
      type: 'category',
      label: 'ROS 2 Robotic Nervous System',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: ROS 2 Architecture',
          items: [
            'ros2-architecture/index',
            'ros2-architecture/role-of-ros2',
            'ros2-architecture/nodes-topics-services',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Python Robot Control (rclpy)',
          items: [
            'python-robot-control/index',
            'python-robot-control/creating-nodes',
            'python-robot-control/pub-sub-patterns',
            'python-robot-control/ai-agent-integration',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Humanoid Structure with URDF',
          items: [
            'urdf-humanoid-structure/index',
            'urdf-humanoid-structure/urdf-links-joints',
            'urdf-humanoid-structure/kinematics',
            'urdf-humanoid-structure/simulation-control',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
