openapi: 3.0.0
info:
  title: Digital Twin Simulation API
  description: API for interacting with digital twin simulation environments
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /environments:
    get:
      summary: List available simulation environments
      description: Retrieve a list of all available digital twin environments
      responses:
        '200':
          description: List of simulation environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SimulationEnvironment'
    post:
      summary: Create a new simulation environment
      description: Create a new digital twin environment with specified parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationEnvironment'
      responses:
        '201':
          description: Environment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationEnvironment'

  /environments/{envId}:
    get:
      summary: Get environment details
      description: Retrieve details about a specific simulation environment
      parameters:
        - name: envId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the environment
      responses:
        '200':
          description: Environment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationEnvironment'
    put:
      summary: Update environment configuration
      description: Update the configuration of a simulation environment
      parameters:
        - name: envId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationEnvironment'
      responses:
        '200':
          description: Environment updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationEnvironment'

  /environments/{envId}/robots:
    get:
      summary: List robots in environment
      description: Retrieve a list of robots in the specified environment
      parameters:
        - name: envId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the environment
      responses:
        '200':
          description: List of robots in the environment
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RobotModel'
    post:
      summary: Add robot to environment
      description: Add a robot model to the simulation environment
      parameters:
        - name: envId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RobotModel'
      responses:
        '201':
          description: Robot added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotModel'

  /environments/{envId}/sensors:
    get:
      summary: List sensors in environment
      description: Retrieve a list of simulated sensors in the environment
      parameters:
        - name: envId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the environment
      responses:
        '200':
          description: List of sensors in the environment
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorData'

components:
  schemas:
    SimulationEnvironment:
      type: object
      required:
        - id
        - name
        - physics_parameters
      properties:
        id:
          type: string
          description: Unique identifier for the environment
        name:
          type: string
          description: Human-readable name of the environment
        description:
          type: string
          description: Detailed description of the environment
        physics_parameters:
          $ref: '#/components/schemas/PhysicsParameters'
        created_at:
          type: string
          format: date-time
          description: When the environment was created
        updated_at:
          type: string
          format: date-time
          description: When the environment was last updated

    PhysicsParameters:
      type: object
      properties:
        gravity:
          type: array
          items:
            type: number
            format: float
          description: Gravity vector [x, y, z] in m/s²
          example: [0, 0, -9.81]
        time_step:
          type: number
          format: float
          description: Simulation time step in seconds
          example: 0.001
        collision_detection:
          type: string
          enum: [ode, bullet, dart]
          description: Collision detection engine to use

    RobotModel:
      type: object
      required:
        - id
        - urdf_path
      properties:
        id:
          type: string
          description: Unique identifier for the robot model
        name:
          type: string
          description: Human-readable name of the robot
        urdf_path:
          type: string
          description: Path to the URDF description file
        joint_count:
          type: integer
          description: Number of joints in the robot
        sensor_mounts:
          type: array
          items:
            type: string
          description: List of sensor mount points on the robot

    SensorData:
      type: object
      required:
        - id
        - sensor_type
        - topic_name
      properties:
        id:
          type: string
          description: Unique identifier for the sensor
        sensor_type:
          type: string
          enum: [lidar, depth_camera, imu, camera, gps]
          description: Type of sensor
        topic_name:
          type: string
          description: ROS 2 topic name for sensor data
        update_rate:
          type: number
          format: float
          description: Sensor update rate in Hz
        data_format:
          type: string
          description: ROS 2 message type for sensor data